//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registr.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Registr.Resources.Texts.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОДАТИ ВИТРАТИ.
        /// </summary>
        internal static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОДАТИ ДОХОДИ.
        /// </summary>
        internal static string AddIncome {
            get {
                return ResourceManager.GetString("AddIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматичне синхронізування.
        /// </summary>
        internal static string AutoSync {
            get {
                return ResourceManager.GetString("AutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планування бюджету.
        /// </summary>
        internal static string BudgetPlanning {
            get {
                return ResourceManager.GetString("BudgetPlanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купити.
        /// </summary>
        internal static string BuyButton {
            get {
                return ResourceManager.GetString("BuyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Криптовалюта.
        /// </summary>
        internal static string Cryptocurrency {
            get {
                return ResourceManager.GetString("Cryptocurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темна тема.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безпека даних.
        /// </summary>
        internal static string DataSecurity {
            get {
                return ResourceManager.GetString("DataSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошта.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розваги.
        /// </summary>
        internal static string Entertainment {
            get {
                return ResourceManager.GetString("Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ІСТОРІЯ ВИТРАТ.
        /// </summary>
        internal static string ExpenseHistory {
            get {
                return ResourceManager.GetString("ExpenseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ВИТРАТИ.
        /// </summary>
        internal static string EXPENSES {
            get {
                return ResourceManager.GetString("EXPENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забули пароль?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукти.
        /// </summary>
        internal static string Groceries {
            get {
                return ResourceManager.GetString("Groceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головна.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДОХІД.
        /// </summary>
        internal static string INCOME {
            get {
                return ResourceManager.GetString("INCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Історія доходів.
        /// </summary>
        internal static string IncomeHistory {
            get {
                return ResourceManager.GetString("IncomeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сповіщення.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персоналізовані анаталітики.
        /// </summary>
        internal static string PersonalAnalytics {
            get {
                return ResourceManager.GetString("PersonalAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифи.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіти.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарплата.
        /// </summary>
        internal static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти зміни.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НАЛАШТУВАННЯ.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтримка спільного бюджету.
        /// </summary>
        internal static string SharedBudgetSupport {
            get {
                return ResourceManager.GetString("SharedBudgetSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 МІСЯЦЬ.
        /// </summary>
        internal static string SubscriptionPeriod {
            get {
                return ResourceManager.GetString("SubscriptionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спробувати безкоштовно.
        /// </summary>
        internal static string TryFree {
            get {
                return ResourceManager.GetString("TryFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс гаманця:.
        /// </summary>
        internal static string WalletBalance {
            get {
                return ResourceManager.GetString("WalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо, user!.
        /// </summary>
        internal static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
    }
}
